api:
  build: ./st2api
  links:
    - mongo
    - rabbitmq
  volumes_from:
    - data

auth:
  build: ./st2auth
  links:
    - api
    - mongo
  volumes_from:
    - data

stream:
  build: ./st2stream
  links:
    - mongo
    - rabbitmq
  volumes_from:
    - data

notifier:
  build: ./st2notifier
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

resultstracker:
  build: ./st2resultstracker
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

rulesengine:
  build: ./st2rulesengine
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

sensorcontainer:
  build: ./st2sensorcontainer
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

garbagecollector:
  build: ./st2garbagecollector
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

exporter:
  build: ./st2exporter
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

actionrunner:
  build: ./st2actionrunner
  links:
    - api
    - auth
    - mongo
    - rabbitmq
  volumes_from:
    - data

## External Services
mongo:
  image: mongo

rabbitmq:
  image: rabbitmq

## Data container
data:
  build: ./data
  volumes:
    - /etc/st2
    - /opt/stackstorm
  links:
    - rabbitmq
    - mongo

## Client container
client:
  build: ./client
  links:
    - api
    - auth
